import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

import { Provider } from "~/components/ui/provider"
import { Container } from "@chakra-ui/react"

export default function RootLayout(props: { children: React.ReactNode }) {
    const { children } = props
    return (
        <html suppressHydrationWarning>
            <body>
                <Provider forcedTheme={"light"}>
                    <Container maxW={{ lgDown: "100%", lg: "50%" }} centerContent p={10}>
                        {children}
                    </Container>
                </Provider>
            </body>
        </html>
    )
}
